# Generated by Django 4.1.4 on 2022-12-15 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Healing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('G', 'Healthy'), ('N', 'Needs Healing')], default='G', max_length=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.character')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
