# Generated by Django 4.1.4 on 2022-12-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healing',
            name='status',
            field=models.CharField(choices=[('G', 'Healthy'), ('N', 'Needs Healing')], max_length=1),
        ),
    ]
