# Generated by Django 4.1.4 on 2022-12-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(to='main_app.weapon'),
        ),
    ]
