# Generated by Django 4.1.4 on 2022-12-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_character_weapons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='color',
        ),
        migrations.AddField(
            model_name='weapon',
            name='damage',
            field=models.TextField(default='2d8 radiant', max_length=100),
            preserve_default=False,
        ),
    ]
