# Generated by Django 4.1.4 on 2022-12-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_healing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healing',
            name='status',
            field=models.CharField(choices=[('H', 'Healthy'), ('N', 'Under Half'), ('L', 'Low'), ('U', 'Unconcious'), ('D', 'Dead')], max_length=1),
        ),
    ]
